name: Nightlies
on:
  push:
    branches:
      - devel

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            triple: x86_64-linux-musl
          - os: linux
            triple: i686-linux-musl
          - os: linux
            triple: aarch64-linux-musl
          - os: linux
            triple: armv7l-linux-musleabihf
          - os: macosx
            triple: x86_64-apple-darwin14
          - os: windows
            triple: x86_64-w64-mingw32
          - os: windows
            triple: i686-w64-mingw32
        include:
          - target:
              os: linux
            builder: ubuntu-18.04
          - target:
              os: macosx
            builder: macos-10.15
          - target:
              os: windows
            builder: windows-2019

    name: '${{ matrix.target.triple }} (${{ matrix.setting.branch }}, ${{ matrix.setting.commit }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout Nim
        uses: actions/checkout@v2
        with:
          repository: nim-lang/Nim
          path: nim

      - name: Checkout Nim csources
        uses: actions/checkout@v2
        with:
          repository: nim-lang/csources_v1
          path: nim/csources_v1

      - name: Build Nim
        working-directory: nim/csources_v1
        shell: bash
        run: |
          echo ${{ matrix.target.triple }}
          
          make --jobs
          
          cd ../
          
          ./bin/nim compile ./koch.nim
          ./koch boot
          ./koch nimble
          
          echo "${PWD}/bin" >> "${GITHUB_PATH}"

      - name: Build Unalix
        uses: actions/checkout@v2
        run: |
          nim compile \
            --opt:'speed' \
            --define:'strip' \
            --define:'danger' \
            --panics:'on' \
            --gc:'orc' \
            --passC:'-Ofast' \
            --passC:'-fwhole-program' \
            --passC:'-flto=full' \
            'src/unalixpkg/main.nim'