name: Nim tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-latest
        ]
        nim-version: [
            "stable",
            "1.4.8",
            "1.4.6",
            "1.4.4",
            "1.4.2",
            "1.4.0",
            "1.2.12",
            "1.2.10",
            "1.2.8"
        ]

    steps:
    - uses: actions/checkout@main
    - name: Set up Nim ${{ matrix.nim-version }}
      uses: jiro4989/setup-nim-action@master
      with:
        nim-version: ${{ matrix.nim-version }}
    - name: Run tests
      run: nimble test
