name: Nim tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: [
            "stable",
            "1.6.0",
            "1.4.0"
        ]

    steps:
    - uses: actions/checkout@main
    - name: Set up Nim ${{ matrix.nim-version }}
      uses: jiro4989/setup-nim-action@master
      with:
        nim-version: ${{ matrix.nim-version }}
    - name: Run tests
      run: nimble test
